# Generated by Django 4.2 on 2024-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_recorditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='items',
        ),
        migrations.AddField(
            model_name='record',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
